Repository CliMA/ParameterEstimocean.jl, pull requests merged in 2021-12, with the labels that each got.

#89 Better UKI docstring formatting
  src/EnsembleKalmanInversions.jl
Labels: documentation

#92 Beautify figure in Docs/InverseProblem
  examples/intro_to_inverse_problems.jl
Labels: documentation

#103 Rename `transform_observations` -> `transform_time_series` and `OneDimensionalTimeSeries` -> `SyntheticObservations`
  examples/calibrate_CATKE_to_LESbrary/lesbrary_paths.jl
  examples/calibrate_CATKE_to_LESbrary/one_dimensional_ensemble_model.jl
  examples/calibrate_CATKE_to_LESbrary/perfect_model_calibration.jl
  examples/calibrate_CATKE_to_LESbrary/visualize_profile_predictions.jl
  examples/intro_to_inverse_problems.jl
  examples/intro_to_observations.jl
  examples/perfect_baroclinic_adjustment_calibration.jl
  examples/perfect_catke_calibration.jl
  examples/perfect_convective_adjustment_calibration.jl
  examples/unscented_perfect_convective_adjustment_calibration.jl
  src/InverseProblems.jl
  src/Observations.jl
  src/OceanTurbulenceParameterEstimation.jl
  src/normalization.jl
  test/test_forward_map.jl
  test/test_one_dimensional_time_series.jl
Labels: cleanup

#106 Minor code formatting
  src/EnsembleKalmanInversions.jl
  src/InverseProblems.jl
Labels: cleanup

#105 Minor fix for `IterationSummary`
  src/EnsembleKalmanInversions.jl
Labels: documentation, cleanup

#107 Tests for `closure_with_parameters` and `update_closure_ensemble_member!`
  Project.toml
  src/TurbulenceClosureParameters.jl
  test/runtests.jl
  test/test_ensemble_column_models.jl
  test/test_forward_map.jl
  test/test_synthetic_observations.jl
  test/test_turbulence_closure_parameters.jl
Labels: tests

#108 Adds a `parameter_ensemble` utility
  examples/perfect_convective_adjustment_calibration.jl
  src/EnsembleKalmanInversions.jl
Labels: 🚰 user experience

#111 Fix iteration counting by `iterate!`
  examples/perfect_baroclinic_adjustment_calibration.jl
  examples/perfect_catke_calibration.jl
  examples/perfect_convective_adjustment_calibration.jl
  src/EnsembleKalmanInversions.jl
Labels: 🚰 user experience

#114 Update dependencies
  Manifest.toml
  Project.toml
  docs/Manifest.toml
  docs/Project.toml
  examples/perfect_baroclinic_adjustment_calibration.jl
Labels: 📦 package
