Repository CliMA/ParameterEstimocean.jl, pull requests merged in 2021-11, with the labels that each got.

#36 Fix bug in `convective_adjustment_perfect_model_calibration.jl`
  examples/convective_adjustment_perfect_model_calibration.jl
Labels: bug

#41 Fix single ensemble member tests for `forward_map`
  test/test_forward_map.jl
Labels: tests

#31 Adds baroclinic adjustment calibration
  .gitignore
  Manifest.toml
  Project.toml
  examples/baroclinic_adjustment_perfect_model_calibration.jl
  src/EnsembleKalmanInversions.jl
  src/InverseProblems.jl
  src/Observations.jl
  src/TurbulenceClosureParameters.jl
Labels: documentation, enhancement

#61 Update installation instructions
  docs/src/installation_instructions.md
Labels: documentation

#72 Some fixes/enhancements in few docstrings
  src/EnsembleKalmanInversions.jl
Labels: documentation

#74 All tests for `forward_map` now run and pass
  src/InverseProblems.jl
  test/convective_adjustment_test.jld2
  test/forward_map_test.jld2
  test/test_forward_map.jl
Labels: tests

#75 Example streamlining
  .github/workflows/Documenter.yml
  .gitignore
  docs/Manifest.toml
  docs/Project.toml
  docs/make.jl
  examples/convective_adjustment.jld2
  examples/convective_adjustment_perfect_model_calibration_eki.jl
  examples/convective_adjustment_perfect_model_calibration_uki.jl
  examples/intro_to_inverse_problems.jl
  examples/intro_to_observations.jl
  examples/perfect_baroclinic_adjustment_calibration.jl
  examples/perfect_convective_adjustment_calibration.jl
  examples/unscented_perfect_convective_adjustment_calibration.jl
  src/EnsembleKalmanInversions.jl
  src/InverseProblems.jl
Labels: documentation
