Repository CliMA/ParameterEstimocean.jl, pull requests merged in 2022-02, with the labels that each got.

#155 Remove Codecov annotations
  codecov.yml
  src/EnsembleKalmanInversions.jl
Labels: 🪤 tests, 📦 package

#154 More general `Resampler`
  Project.toml
  examples/five_case_catke_calibration.jl
  examples/lesbrary_catke_calibration.jl
  src/EnsembleKalmanInversions.jl
  src/Observations.jl
  src/OceanTurbulenceParameterEstimation.jl
  test/runtests.jl
  test/test_ensemble_kalman_inversion.jl
Labels: 🐞 bug, 🤥 enhancement

#159 Calibrate `IsopycnalSkewSymmetricDiffusivity` in eddying channel
  examples/calibrate_zonally_averaged_channel.jl
  src/TurbulenceClosureParameters.jl
  test/test_turbulence_closure_parameters.jl
Labels: 🚑 help wanted

#161 Priors API refactor
  Project.toml
  docs/src/library/internals.md
  docs/src/library/public.md
  examples/five_case_catke_calibration.jl
  examples/intro_to_inverse_problems.jl
  examples/lesbrary_catke_calibration.jl
  examples/perfect_baroclinic_adjustment_calibration.jl
  examples/perfect_catke_calibration.jl
  examples/perfect_convective_adjustment_calibration.jl
  examples/visualize_distributions.jl
  src/EnsembleKalmanInversions.jl
  src/InverseProblems.jl
  src/Observations.jl
  src/OceanTurbulenceParameterEstimation.jl
  src/Parameters.jl
  test/test_ensemble_kalman_inversion.jl
  test/test_turbulence_closure_parameters.jl
Labels: 🧹 cleanup, 🚰 user experience

#177 Introducing `Transformation` encompassing normalization, time slicing/weighting, and space slicing/weighting
  examples/calibrate_zonally_averaged_channel.jl
  examples/five_case_catke_calibration.jl
  examples/intro_to_inverse_problems.jl
  examples/intro_to_observations.jl
  examples/lesbrary_catke_calibration.jl
  examples/perfect_baroclinic_adjustment_calibration.jl
  examples/perfect_catke_calibration.jl
  examples/perfect_convective_adjustment_calibration.jl
  src/InverseProblems.jl
  src/Observations.jl
  src/OceanTurbulenceParameterEstimation.jl
  src/Transformations.jl
  src/normalization.jl
  test/test_forward_map.jl
  test/test_lesbrary_forward_map.jl
  test/test_synthetic_observations.jl
Labels: 🚰 user experience

#180 Some fixes in the perfect baroclinic adjustment calibration example
  Project.toml
  examples/perfect_baroclinic_adjustment_calibration.jl
Labels: 📔 documentation

#181 Delete bug_test.jl
  examples/calibrate_to_LESbrary/bug_test.jl
Labels: 🧹 cleanup

#183 More resampler tests...
  test/test_ensemble_kalman_inversion.jl
Labels: 🪤 tests

#182 Adds some tests for Transformations
  Project.toml
  README.md
  examples/perfect_baroclinic_adjustment_calibration.jl
  src/OceanTurbulenceParameterEstimation.jl
  src/Transformations.jl
  test/runtests.jl
  test/test_transformations.jl
Labels: 🪤 tests

#184 Better latex rendering + update installation instructions in Docs
  docs/src/installation_instructions.md
  src/EnsembleKalmanInversions.jl
  src/Parameters.jl
Labels: 📔 documentation

#186 Moar docstrings
  src/InverseProblems.jl
  src/Observations.jl
  src/Parameters.jl
  src/Transformations.jl
Labels: 📔 documentation

#188 Adds Transform tests for weighting
  src/Transformations.jl
  test/test_transformations.jl
Labels: 🐞 bug, 🪤 tests

#193 Adding a docstring to `Transformation`
  examples/perfect_catke_calibration.jl
  src/Transformations.jl
Labels: 📔 documentation

#192 Makes Perfect CATKE example cheaper
  examples/perfect_catke_calibration.jl
Labels: 📔 documentation

#200 Restructuring of Docs
  docs/make.jl
Labels: 📔 documentation

#203 Use latest Oceananigans with prettytime shenanigans
  Manifest.toml
  Project.toml
  docs/Manifest.toml
  docs/Project.toml
Labels: 📦 package

#201 Docs don't need ElectronDisplay
  docs/Manifest.toml
  docs/Project.toml
Labels: 📦 package

#199 Properly export functions from submodules
  docs/src/library/internals.md
  docs/src/library/public.md
  src/EnsembleKalmanInversions.jl
  src/EnsembleSimulations.jl
  src/InverseProblems.jl
  src/Observations.jl
  src/OceanTurbulenceParameterEstimation.jl
  src/Parameters.jl
  src/Transformations.jl
Labels: 📔 documentation

#205 Fix `prettyvector` which is used in `show(io, ::SyntheticObservations)`
  src/Utils.jl
  test/runtests.jl
  test/test_utils.jl
Labels: 🚰 user experience

#209 Some clean up of some suppressions
  src/EnsembleKalmanInversions.jl
  src/InverseProblems.jl
Labels: 🧹 cleanup

#210 Zero out time series tendency data !!
  Project.toml
  src/EnsembleKalmanInversions.jl
  src/InverseProblems.jl
  src/Observations.jl
  test/test_ensemble_kalman_inversion.jl
  test/test_forward_map.jl
Labels: 🐞 bug

#214 New update ensemble method + adaptive time-stepping
  Manifest.toml
  Project.toml
  examples/five_case_catke_calibration.jl
  examples/perfect_baroclinic_adjustment_calibration.jl
  src/EnsembleKalmanInversions.jl
  src/iteration_summary.jl
  src/resampling.jl
Labels: 🤥 enhancement
