Repository CliMA/ParameterEstimocean.jl, pull requests merged in 2022-01, with the labels that each got.

#117 Fix bug when running `forward_map` twice
  Manifest.toml
  docs/Manifest.toml
  src/InverseProblems.jl
  src/Observations.jl
  test/runtests.jl
  test/test_forward_map.jl
Labels: 🪤 tests

#100 Perfect calibration of CATKE
  docs/make.jl
  examples/intro_to_inverse_problems.jl
  examples/intro_to_observations.jl
  examples/perfect_baroclinic_adjustment_calibration.jl
  examples/perfect_catke_calibration.jl
  src/EnsembleKalmanInversions.jl
  src/InverseProblems.jl
Labels: 📔 documentation

#121 Fix limits in scatter and pdf figure for CATKE perfect model calibration
  examples/perfect_catke_calibration.jl
Labels: 📔 documentation

#102 Implements NaNResampler
  Manifest.toml
  Project.toml
  docs/Manifest.toml
  docs/Project.toml
  examples/calibrate_to_LESbrary/calibrate_catke_to_perfect_model.jl
  src/EnsembleKalmanInversions.jl
  src/InverseProblems.jl
  src/Observations.jl
  src/OceanTurbulenceParameterEstimation.jl
  test/runtests.jl
  test/test_eki.jl
  test/test_synthetic_observations.jl
Labels: 🧹 cleanup

#123 Upgrade to latest Oceananigans and get running on the GPU
  Manifest.toml
  Project.toml
  examples/intro_to_inverse_problems.jl
  examples/intro_to_observations.jl
  examples/perfect_catke_calibration.jl
  src/InverseProblems.jl
  src/Observations.jl
  src/TurbulenceClosureParameters.jl
  test/test_forward_map.jl
Labels: 🎮 gpu

#139 Add back compat entries
  Project.toml
  docs/make.jl
Labels: 📦 package

#141 Update packages
  Manifest.toml
  Project.toml
  docs/Manifest.toml
  docs/Project.toml
Labels: 📦 package

#128 LESbrary calibration example + refactor `iterate!`
  Manifest.toml
  Project.toml
  docs/Manifest.toml
  docs/Project.toml
  docs/make.jl
  examples/lesbrary_catke_calibration.jl
  examples/two_case_catke_calibration.jl
  examples/unscented_perfect_convective_adjustment_calibration.jl
  src/EnsembleKalmanInversions.jl
  src/EnsembleSimulations.jl
  src/InverseProblems.jl
  src/Observations.jl
  src/OceanTurbulenceParameterEstimation.jl
  test/test_synthetic_observations.jl
Labels: 📔 documentation

#142 Update docstrings
  src/EnsembleKalmanInversions.jl
Labels: 📔 documentation

#150 Five case calibration "example" and a few GPU fixes
  Manifest.toml
  Project.toml
  docs/Manifest.toml
  docs/Project.toml
  examples/five_case_catke_calibration.jl
  examples/two_case_catke_calibration.jl
  src/Observations.jl
  src/Utils.jl
Labels: 🐞 bug, 📔 documentation
