Repository CliMA/ParameterEstimocean.jl, pull requests merged in 2022-06, with the labels that each got.

#271 Implement dependent parameters feature for `FreeParameters`
  Project.toml
  docs/Manifest.toml
  docs/Project.toml
  src/EnsembleKalmanInversions.jl
  src/InverseProblems.jl
  src/Parameters.jl
  src/iteration_summary.jl
Labels: 🤥 enhancement

#276 Fix incremental compilation error for `NormExceedsMedian`
  src/EnsembleKalmanInversions.jl
Labels: 🐞 bug

#277 Deploy Docs to CliMA/ParameterEstimoceanDocumentation repo
  .github/workflows/DocPreviewCleanup.yml
  .github/workflows/Documenter.yml
  .github/workflows/ci.yml
  Manifest.toml
  Project.toml
  docs/Manifest.toml
  docs/Project.toml
  docs/make.jl
  src/InverseProblems.jl
Labels: 📔 documentation, 📦 package

#281 Give Doc Preview Cleanup access to CliMA/ParameterEstimoceanDocumentation
  .github/workflows/DocPreviewCleanup.yml
Labels: 📔 documentation, 📦 package

#282 Update doc urls
  README.md
  docs/make.jl
Labels: 📔 documentation

#270 BatchedSyntheticObservations with optional weights
  examples/multi_case_lesbrary_ri_based_calibration.jl
  src/EnsembleSimulations.jl
  src/InverseProblems.jl
  src/Observations.jl
  src/ParameterEstimocean.jl
  test/test_ensemble_kalman_inversion.jl
  test/test_forward_map.jl
  test/test_synthetic_observations.jl
Labels: 🤥 enhancement

#287 Remove blood reference from `README`
  README.md
Labels: 📔 documentation
